UPDATE placements SET notes = '[
  {"id":"1725209880000","content":"<p>Guten Tag Herr Aradini</p><p>Vielen Dank für die Infos und dem Dossier.</p><p>Wir haben Interesse am Kandidaten und würden diesen gerne kennenlernen. Betreffend Salär Vorstellung, wir haben keine Lohnbänder. Seine Fähigkeiten sind mit der Salär Vorstellung zu prüfen.</p><p>Die AGB sind ebenfalls okay. Wobei wir erst nach erfolgreicher Probezeit bereit sind das Vermittlungshonorar zu vergüten.</p><p>Besten Dank für die Rückmeldung und einen schönen Tag.</p><p>Freundliche Grüsse<br>LBM Partner AG</p><p>Marcel Wechsler<br>Tel. 041 555 53 82<br>marcel.wechsler@lbm-partner.ch</p>","author":"Flo","timestamp":"2025-09-01T18:38:00.000Z","isImportant":false},
  {"id":"1725209880001","content":"<p>Guten Tag Herr Wechsler</p><p>Vielen Dank für Ihre schnelle Rückmeldung und das Interesse an Herr Reinold.</p><p>Gerne teile ich Ihnen die Kontaktdaten von Herr Reinold zur Koordinierung eines ersten Gespräches mit.</p><p>Zuerst müssen wir uns jedoch bzgl. des Vergütungszeitpunktes des Vermittlungshonorars einig werden. Dies ist für uns nämlich nach Ihrem Vorschlag nicht möglich.</p><p>Das Vergütungshonorar wäre wie üblich bei Vertragsunterschrift fällig. Änderungen können wir diesbezüglich nicht vornehmen.</p><p>Was ich Ihnen jedoch anbieten kann, ist die Garantiereglung etwas anzupassen, damit wir Ihnen entgegenkommen können:</p><p>1. Monat 60% Rückerstattung<br>2. Monat 40%<br>3. Monat 40%</p><p>Geben Sie mir Bescheid, ob das so für Sie in Ordnung ist, dann können wir fortfahren.</p><p>Freundliche Grüsse<br>Florent</p>","author":"Flo","timestamp":"2025-09-01T18:38:01.000Z","isImportant":false},
  {"id":"1725209880002","content":"<p>Reinold weiss noch nicht Bescheid</p>","author":"Flo","timestamp":"2025-09-01T18:38:02.000Z","isImportant":false},
  {"id":"1725267060000","content":"<p>Guten Morgen Herr Aradini</p><p>Besten Dank für die Rückmeldung.</p><p>Gegebenenfalls werden wir uns auf Grund des Bewerbungsgespräch zu diesem Punkt nochmals melden.</p><p>Für den Moment so okay.</p><p>Freundliche Grüsse<br>LBM Partner AG</p><p>Marcel Wechsler<br>Tel. 041 555 53 82<br>marcel.wechsler@lbm-partner.ch</p><p>LBM Partner AG<br>Stadthofstrasse 4<br>CH – 6004 Luzern<br>Tel. 041 555 53 80</p>","author":"Flo","timestamp":"2025-09-02T10:31:00.000Z","isImportant":false},
  {"id":"1725272820000","content":"<p>Felix wurde informiert und Kontaktdaten an Herr Wechsler geteilt. Felix bekommt noch Expose als Info und Vorbereitung</p>","author":"Flo","timestamp":"2025-09-02T12:07:00.000Z","isImportant":false},
  {"id":"1725439920000","content":"<p>Interview 1: Montag, 8. September 2025 um 16:30 - 17:30 vor Ort in Luzern</p>","author":"Flo","timestamp":"2025-09-04T10:32:00.000Z","isImportant":false},
  {"id":"1725799260000","content":"<p>1. Interview wurde auf Freitag verschoben</p>","author":"Flo","timestamp":"2025-09-08T14:41:00.000Z","isImportant":false},
  {"id":"1726066680000","content":"<p>Sali Felix</p><p>Ich wünsche dir morgen viel Erfolg für dein Gespräch. Bitte schau dir nochmal das Expose an eventuell, kannst du dich etwas inspirieren lassen davon 😉.</p><p>Es ist super wichtig, dass du dich darauf vorbereitest und der Firma zeigst, dass du dich mit ihnen beschäftigt hast.</p><p>Hast du sonst Interesse, dass wir nochmal gemeinsam über die Firma reden?</p>","author":"Flo","timestamp":"2025-09-11T14:58:00.000Z","isImportant":false},
  {"id":"1726068480000","content":"<p>Hat sich anscheinend vorbereitet. Mal schauen</p>","author":"Max","timestamp":"2025-09-11T15:28:00.000Z","isImportant":false},
  {"id":"1726391880000","content":"<p>Feedback von Felix auf Whatsapp:</p><p>[12.09.25, 21:51:56] Felix Reinold: Hey Florent, also kurzes Feedback. Das Gespräch war wirklich gut, hat mir sehr gefallen was ich gehört habe. War mit Marcel Wechsler auch direkt auf einer Wellenlänge 👍🏻 werde mir übers WE nochmal etwas Gedanken machen.</p><p>[12.09.25, 21:53:29] Felix Reinold: Er meinte selber, er hatte sich nicht viel erhofft, aber ich habe ihn sehr überrascht.</p><p>[12.09.25, 21:53:42] Felix Reinold: Beste Grüsse und schönes WE</p>","author":"Max","timestamp":"2025-09-15T10:18:00.000Z","isImportant":false},
  {"id":"1726392480000","content":"<p>Feedback von Marcel Wechsler (Firma):</p><p>Gespräch ist sehr gut verlaufen<br>Zwischenmenschlich hat es von seiner Seite auch extrem gut gepasst<br>Er hat Felix gesagt er soll sich in den nächsten Tagen melden also spätestens bis Mittwoch<br>Wenn Felix den Prozess fortführen möchte, wird es ein zweites Gespräch geben oder sogar schon ein erstes Vertragsangebot<br>Auf die Frage ob es Kritikpunkte gibt, meinte Herr Wechsler, dass er nicht weiss ob Felix die Erwartungen erfüllen wird - ist aber bei jedem Kandidaten so</p>","author":"Flo","timestamp":"2025-09-15T10:28:00.000Z","isImportant":false},
  {"id":"1726392540000","content":"<p>Felix tne</p>","author":"Flo","timestamp":"2025-09-15T10:29:00.000Z","isImportant":false},
  {"id":"1726418640000","content":"<p>Telefonischer Austausch mit Felix:</p><p>Gehalt wird sich um die 125k drehen<br>Er würde anscheinend auch Spesen und einen der Poolwagen bekommen<br>Wird sich morgen beim Herr Wechsler melden und ihm Bescheid geben, dass er es sich gut vorstellen kann bei ihnen zu arbeiten und interessiert ist</p>","author":"Flo","timestamp":"2025-09-15T17:44:00.000Z","isImportant":false},
  {"id":"1727020500000","content":"<p>Status Felix:</p><p>Wurde geisteskrank von der Firma beeinflusst</p><p>Wie besprochen übermittle ich Ihnen noch eine kurze Zusammenfassung der aktuellen Situation.</p><p>Email an Wechsler (hatte mich mit ihm auch telefonisch ausgetauscht):</p><p>Felix Reinold hat sich vor knapp einer Stunde bei mir gemeldet und mir die aktuelle Situation geschildert. Er hat leider 1-2 Arbeitskollegen anvertraut, dass er kurz vor einem Wechsel steht. Diese Information ist daraufhin zur Geschäftsleitung der Arcanus gelangt, was Herr Reinold sehr bedauert, da die Geschäftsleitung nun aktiv geworden ist, um ihn in seiner Entscheidung zu beeinflussen.</p><p>Es wurde versucht, bei ihm ein schlechtes Gewissen hervorzurufen, und ihm wurde zudem ein neues Angebot unterbreitet (126.000 CHF Fixgehalt zzgl. Bonus). Diese Massnahmen haben bei ihm verständlicherweise zu grosser Verunsicherung geführt. Zudem wurde ihm signalisiert, dass das aktuelle Projekt ohne ihn möglicherweise nicht fortgesetzt werden was (was natürlich übertrieben dargestellt ist).</p><p>Ich habe Felix ausdrücklich gebeten, sich direkt bei Ihnen zu melden und die Situation offen und transparent zu besprechen. Aus meiner Sicht ist es jetzt entscheidend, dass er von Ihnen die Sicherheit und Perspektive vermittelt bekommt, die er benötigt. Wir wissen beide, dass diese Position bei LBM langfristig die bessere Lösung für ihn darstellt. Zudem weiss ich das Felix interessiert war die Position anzunehmen.</p><p>Sofern es für Sie möglich ist, könnte auch ein überarbeitetes Angebot ein starkes Signal setzen. Dies liegt jedoch ganz in Ihrem Ermessen. Darüber hinaus wäre es hilfreich, wenn Sie im Gespräch mit Felix über zukünftige Projekte und potenzielle Einsatzmöglichkeiten sprechen. So kann er erkennen, dass LBM die nachhaltigere und bessere Wahl ist und seine Entscheidung aus Komfortgründen nicht überstürzt.</p><p>Bitte lassen Sie mich wissen, sobald Sie mit Felix gesprochen haben oder falls Sie weitere Unterstützung von meiner Seite benötigen.</p><p>Freundliche Grüsse<br>Florent</p>","author":"Flo","timestamp":"2025-09-22T16:55:00.000Z","isImportant":false},
  {"id":"1727348760000","content":"<p>Felix Reinold TNE</p>","author":"Flo","timestamp":"2025-09-26T12:06:00.000Z","isImportant":false},
  {"id":"1727355840000","content":"<p>Gründe für das Ablehnen:</p><p>Kandidat hat kein Interesse</p><p>Wechsel wurde aufgeschoben auf 2026</p>","author":"Flo","timestamp":"2025-09-26T14:04:00.000Z","isImportant":false}
]'::jsonb WHERE id = '01bc5168-c904-48fa-9bb1-ee952f03ade0';