// ============================================================
// DEMO MODE SEED DATA
// ------------------------------------------------------------
// This project runs as a fully client-side demo. There is no
// Supabase backend. All data lives in localStorage and is
// seeded from the JSON-like structures below.
// ============================================================

export type DemoRole = "admin" | "manager" | "user" | "viewer" | "candidate";

export interface DemoUser {
  id: string;
  email: string;
  password: string;
  full_name: string;
  role: DemoRole;
  user_type: "internal" | "candidate";
  avatar_url: string | null;
}

// Login accounts shown as quick-login buttons on the auth screen.
export const DEMO_USERS: DemoUser[] = [
  {
    id: "u-admin",
    email: "admin@demo.test",
    password: "demo1234",
    full_name: "Alex Admin",
    role: "admin",
    user_type: "internal",
    avatar_url: null,
  },
  {
    id: "u-manager",
    email: "manager@demo.test",
    password: "demo1234",
    full_name: "Morgan Manager",
    role: "manager",
    user_type: "internal",
    avatar_url: null,
  },
  {
    id: "u-user",
    email: "user@demo.test",
    password: "demo1234",
    full_name: "Riley Recruiter",
    role: "user",
    user_type: "internal",
    avatar_url: null,
  },
  {
    id: "u-viewer",
    email: "viewer@demo.test",
    password: "demo1234",
    full_name: "Vivian Viewer",
    role: "viewer",
    user_type: "internal",
    avatar_url: null,
  },
  {
    id: "u-candidate",
    email: "candidate@demo.test",
    password: "demo1234",
    full_name: "Casey Candidate",
    role: "candidate",
    user_type: "candidate",
    avatar_url: null,
  },
];

const OWNER = "u-admin";

const now = Date.now();
const iso = (offsetDays = 0) =>
  new Date(now - offsetDays * 24 * 60 * 60 * 1000).toISOString();

type Row = Record<string, any>;
export type DemoDatabase = Record<string, Row[]>;

const profiles: Row[] = DEMO_USERS.map((u) => ({
  id: u.id,
  full_name: u.full_name,
  email: u.email,
  avatar_url: u.avatar_url,
  user_type: u.user_type,
  created_at: iso(120),
  updated_at: iso(1),
}));

const user_roles: Row[] = DEMO_USERS.filter((u) => u.user_type === "internal").map(
  (u) => ({
    id: `role-${u.id}`,
    user_id: u.id,
    role: u.role,
    created_at: iso(120),
  })
);

const clients: Row[] = [
  {
    id: "c-1",
    name: "Nordwind Technologies GmbH",
    industry: "Software & IT",
    status: "Partner",
    contact_person: "Sandra Berger",
    email: "hr@nordwind-tech.de",
    phone: "+49 30 1234567",
    website: "https://nordwind-tech.de",
    address: "Friedrichstraße 12, 10117 Berlin",
    description:
      "Leading mid-size software house specialising in cloud platforms and data engineering for the logistics sector.",
    description_approved: true,
    benefits: "Remote-first, 30 days vacation, learning budget, company pension.",
    logo_url: null,
    logo_bg_color: "#1e40af",
    notes: "Strategic partner since 2021. Fast hiring decisions.",
    structured_notes: null,
    careers_url: "https://nordwind-tech.de/careers",
    user_id: OWNER,
    created_at: iso(90),
    updated_at: iso(3),
  },
  {
    id: "c-2",
    name: "Bayerische MedTech AG",
    industry: "Healthcare & MedTech",
    status: "Offen",
    contact_person: "Dr. Thomas Huber",
    email: "karriere@bayern-medtech.de",
    phone: "+49 89 9876543",
    website: "https://bayern-medtech.de",
    address: "Maximilianstraße 4, 80539 München",
    description:
      "Manufacturer of precision medical devices with strong R&D focus and global distribution.",
    description_approved: false,
    benefits: "Flexible hours, on-site gym, relocation support.",
    logo_url: null,
    logo_bg_color: "#0f766e",
    notes: "Looking to scale their embedded software team.",
    structured_notes: null,
    careers_url: null,
    user_id: OWNER,
    created_at: iso(60),
    updated_at: iso(5),
  },
  {
    id: "c-3",
    name: "Rheinland Finanz Solutions",
    industry: "Finance & Insurance",
    status: "Offen",
    contact_person: "Petra Klein",
    email: "jobs@rheinland-finanz.de",
    phone: "+49 221 4567890",
    website: "https://rheinland-finanz.de",
    address: "Hohenzollernring 22, 50672 Köln",
    description:
      "Digital-first financial services provider building modern banking experiences.",
    description_approved: true,
    benefits: "Hybrid work, stock options, public transport ticket.",
    logo_url: null,
    logo_bg_color: "#9333ea",
    notes: "Compliance-driven, longer hiring cycles.",
    structured_notes: null,
    careers_url: null,
    user_id: OWNER,
    created_at: iso(45),
    updated_at: iso(2),
  },
  {
    id: "c-4",
    name: "GreenMobility Hamburg",
    industry: "Mobility & Automotive",
    status: "N/D",
    contact_person: "Lars Petersen",
    email: "talent@greenmobility-hh.de",
    phone: "+49 40 1112223",
    website: "https://greenmobility-hh.de",
    address: "Hafenstraße 8, 20359 Hamburg",
    description: "Sustainable urban mobility startup scaling across Europe.",
    description_approved: false,
    benefits: "Free e-scooter usage, equity, dog-friendly office.",
    logo_url: null,
    logo_bg_color: "#16a34a",
    notes: "New lead, first call scheduled.",
    structured_notes: null,
    careers_url: null,
    user_id: OWNER,
    created_at: iso(15),
    updated_at: iso(1),
  },
];

const contact_persons: Row[] = [
  {
    id: "cp-1",
    client_id: "c-1",
    name: "Sandra Berger",
    position: "Head of People",
    email: "s.berger@nordwind-tech.de",
    phone: "+49 30 1234567",
    mobile: "+49 170 1112233",
    is_primary: true,
    notes: "Main point of contact for all engineering roles.",
    user_id: OWNER,
    created_at: iso(90),
    updated_at: iso(3),
  },
  {
    id: "cp-2",
    client_id: "c-1",
    name: "Jonas Frei",
    position: "Engineering Manager",
    email: "j.frei@nordwind-tech.de",
    phone: "+49 30 1234568",
    mobile: null,
    is_primary: false,
    notes: "Technical interviewer.",
    user_id: OWNER,
    created_at: iso(80),
    updated_at: iso(10),
  },
  {
    id: "cp-3",
    client_id: "c-2",
    name: "Dr. Thomas Huber",
    position: "VP Engineering",
    email: "t.huber@bayern-medtech.de",
    phone: "+49 89 9876543",
    mobile: "+49 171 4445566",
    is_primary: true,
    notes: "Decision maker for the firmware team.",
    user_id: OWNER,
    created_at: iso(60),
    updated_at: iso(5),
  },
  {
    id: "cp-4",
    client_id: "c-3",
    name: "Petra Klein",
    position: "Talent Acquisition Lead",
    email: "p.klein@rheinland-finanz.de",
    phone: "+49 221 4567890",
    mobile: null,
    is_primary: true,
    notes: null,
    user_id: OWNER,
    created_at: iso(45),
    updated_at: iso(2),
  },
];

const candidates: Row[] = [
  {
    id: "cand-1",
    name: "Julia Sommer",
    email: "julia.sommer@example.com",
    phone: "+49 151 23456789",
    position: "Senior Backend Engineer",
    desired_position: "Lead Backend Engineer",
    location: "Berlin",
    industry: "Software & IT",
    status: "Active",
    recruiting_status: "Ready2Push",
    priority: "high",
    experience: "8 years",
    current_salary: "78.000 €",
    desired_salary: "90.000 €",
    notice_period: "3 months",
    willing_to_relocate: "No",
    workload: "Full-time",
    skills: ["Java", "Spring Boot", "Kubernetes", "PostgreSQL", "AWS"],
    languages: [
      { language: "German", level: "Native" },
      { language: "English", level: "C1" },
    ],
    summary:
      "Experienced backend engineer with a strong track record in distributed systems and cloud-native architectures.",
    ai_summary:
      "Julia is a high-potential senior engineer, strong in JVM ecosystems and cloud platforms, ready for a lead role.",
    notes: "Very responsive, open to new opportunities in Q3.",
    source_contact: "Nicola Lube",
    is_verified: true,
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(40),
    updated_at: iso(2),
  },
  {
    id: "cand-2",
    name: "Mehmet Yilmaz",
    email: "mehmet.yilmaz@example.com",
    phone: "+49 152 98765432",
    position: "Embedded Software Developer",
    desired_position: "Embedded Software Developer",
    location: "München",
    industry: "Healthcare & MedTech",
    status: "Active",
    recruiting_status: "Unterlagen geschickt",
    priority: "medium",
    experience: "5 years",
    current_salary: "65.000 €",
    desired_salary: "75.000 €",
    notice_period: "2 months",
    willing_to_relocate: "Yes",
    workload: "Full-time",
    skills: ["C", "C++", "RTOS", "STM32", "Embedded Linux"],
    languages: [
      { language: "Turkish", level: "Native" },
      { language: "German", level: "C1" },
      { language: "English", level: "B2" },
    ],
    summary: "Embedded specialist with medical device experience.",
    ai_summary: "Strong embedded profile, ideal fit for regulated MedTech environments.",
    notes: "Interested in the Bayerische MedTech role.",
    source_contact: "Sebastian Jansche",
    is_verified: true,
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(30),
    updated_at: iso(4),
  },
  {
    id: "cand-3",
    name: "Anna Kowalski",
    email: "anna.kowalski@example.com",
    phone: "+49 160 11223344",
    position: "Frontend Developer",
    desired_position: "Senior Frontend Developer",
    location: "Köln",
    industry: "Finance & Insurance",
    status: "Active",
    recruiting_status: "Unterlagen offen",
    priority: "high",
    experience: "6 years",
    current_salary: "62.000 €",
    desired_salary: "72.000 €",
    notice_period: "6 weeks",
    willing_to_relocate: "No",
    workload: "Full-time",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind"],
    languages: [
      { language: "Polish", level: "Native" },
      { language: "German", level: "C2" },
      { language: "English", level: "C1" },
    ],
    summary: "Product-minded frontend engineer focused on design systems.",
    ai_summary: "Great UI craftsmanship, strong React/TS foundation.",
    notes: null,
    source_contact: "Celine Glabonjat",
    is_verified: false,
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(22),
    updated_at: iso(1),
  },
  {
    id: "cand-4",
    name: "David Lindqvist",
    email: "david.lindqvist@example.com",
    phone: "+46 70 1234567",
    position: "DevOps Engineer",
    desired_position: "Platform Engineer",
    location: "Hamburg",
    industry: "Mobility & Automotive",
    status: "Passive",
    recruiting_status: "Austausch ausstehend",
    priority: "low",
    experience: "7 years",
    current_salary: "80.000 €",
    desired_salary: "88.000 €",
    notice_period: "3 months",
    willing_to_relocate: "Yes",
    workload: "Full-time",
    skills: ["Terraform", "AWS", "Docker", "Kubernetes", "CI/CD"],
    languages: [
      { language: "Swedish", level: "Native" },
      { language: "English", level: "C2" },
      { language: "German", level: "B1" },
    ],
    summary: "Platform engineer with a passion for developer experience.",
    ai_summary: "Solid DevOps generalist, currently passive but open.",
    notes: "Prefers fully remote.",
    source_contact: "Fabian Jansche",
    is_verified: true,
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(18),
    updated_at: iso(6),
  },
  {
    id: "cand-5",
    name: "Sofia Romano",
    email: "sofia.romano@example.com",
    phone: "+49 175 55667788",
    position: "Data Scientist",
    desired_position: "Senior Data Scientist",
    location: "Berlin",
    industry: "Software & IT",
    status: "Active",
    recruiting_status: "Ready2Push",
    priority: "high",
    experience: "4 years",
    current_salary: "68.000 €",
    desired_salary: "80.000 €",
    notice_period: "2 months",
    willing_to_relocate: "No",
    workload: "Full-time",
    skills: ["Python", "PyTorch", "SQL", "MLOps", "Pandas"],
    languages: [
      { language: "Italian", level: "Native" },
      { language: "English", level: "C1" },
      { language: "German", level: "B2" },
    ],
    summary: "ML practitioner with strong MLOps mindset.",
    ai_summary: "Promising data scientist, hands-on with modern ML stacks.",
    notes: null,
    source_contact: "Davide di Cesare",
    is_verified: true,
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(10),
    updated_at: iso(1),
  },
  {
    id: "cand-6",
    name: "Tobias Wagner",
    email: "tobias.wagner@example.com",
    phone: "+49 159 99887766",
    position: "Product Manager",
    desired_position: "Senior Product Manager",
    location: "München",
    industry: "Software & IT",
    status: "N/D",
    recruiting_status: "Austausch ausstehend",
    priority: "medium",
    experience: "9 years",
    current_salary: "92.000 €",
    desired_salary: "105.000 €",
    notice_period: "3 months",
    willing_to_relocate: "Yes",
    workload: "Full-time",
    skills: ["Product Strategy", "Roadmapping", "Agile", "Analytics"],
    languages: [
      { language: "German", level: "Native" },
      { language: "English", level: "C1" },
    ],
    summary: "Seasoned PM bridging business and engineering.",
    ai_summary: "Strong B2B SaaS product leadership background.",
    notes: "First exchange pending.",
    source_contact: "Jacqueline Soel",
    is_verified: false,
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(5),
    updated_at: iso(1),
  },
];

const jobs: Row[] = [
  {
    id: "job-1",
    title: "Lead Backend Engineer (m/w/d)",
    client_id: "c-1",
    location: "Berlin / Remote",
    status: "Active",
    employment_type: "Full-time",
    experience_level: "Senior",
    salary_range: "85.000 – 100.000 €",
    skills: ["Java", "Spring Boot", "Kubernetes", "AWS"],
    description:
      "Lead the backend team building our next-generation logistics cloud platform.",
    requirements: "8+ years backend experience, strong JVM and cloud skills, leadership experience.",
    responsibilities: "Own architecture, mentor engineers, drive technical roadmap.",
    benefits: "Remote-first, 30 days vacation, learning budget.",
    publication_status: "draft",
    publication_language: "de",
    anonymization_level: "none",
    active_variant: "a",
    active_title_variant: "a",
    auto_optimize: false,
    is_published: false,
    seo_keywords: ["backend", "java", "berlin"],
    user_id: OWNER,
    assigned_to: OWNER,
    created_at: iso(35),
    updated_at: iso(2),
  },
  {
    id: "job-2",
    title: "Embedded Software Developer (m/w/d)",
    client_id: "c-2",
    location: "München",
    status: "Offen",
    employment_type: "Full-time",
    experience_level: "Mid",
    salary_range: "70.000 – 80.000 €",
    skills: ["C", "C++", "RTOS", "Embedded Linux"],
    description: "Develop firmware for life-saving medical devices.",
    requirements: "5+ years embedded experience, ideally in regulated environments.",
    responsibilities: "Design and implement firmware, collaborate with hardware team.",
    benefits: "Flexible hours, on-site gym, relocation support.",
    publication_status: "published",
    publication_language: "de",
    anonymization_level: "partial",
    active_variant: "a",
    active_title_variant: "a",
    auto_optimize: false,
    is_published: true,
    published_at: iso(8),
    publication_expires_at: iso(-22),
    seo_keywords: ["embedded", "medtech", "münchen"],
    user_id: OWNER,
    assigned_to: OWNER,
    created_at: iso(28),
    updated_at: iso(5),
  },
  {
    id: "job-3",
    title: "Senior Frontend Developer (m/w/d)",
    client_id: "c-3",
    location: "Köln / Hybrid",
    status: "Assignment",
    employment_type: "Full-time",
    experience_level: "Senior",
    salary_range: "68.000 – 78.000 €",
    skills: ["React", "TypeScript", "Next.js"],
    description: "Build modern digital banking experiences.",
    requirements: "6+ years frontend, strong React/TS, design system experience.",
    responsibilities: "Develop UI components, ensure accessibility and performance.",
    benefits: "Hybrid work, stock options, public transport ticket.",
    publication_status: "draft",
    publication_language: "de",
    anonymization_level: "none",
    active_variant: "a",
    active_title_variant: "a",
    auto_optimize: false,
    is_published: false,
    seo_keywords: ["frontend", "react", "köln"],
    user_id: OWNER,
    assigned_to: OWNER,
    created_at: iso(20),
    updated_at: iso(1),
  },
  {
    id: "job-4",
    title: "Platform / DevOps Engineer (m/w/d)",
    client_id: "c-4",
    location: "Hamburg / Remote",
    status: "Offen",
    employment_type: "Full-time",
    experience_level: "Senior",
    salary_range: "80.000 – 95.000 €",
    skills: ["Terraform", "AWS", "Kubernetes", "CI/CD"],
    description: "Own the cloud platform for a fast-scaling mobility startup.",
    requirements: "7+ years infrastructure, IaC mastery, platform mindset.",
    responsibilities: "Build self-service platform, improve developer experience.",
    benefits: "Equity, free e-scooter usage, dog-friendly office.",
    publication_status: "draft",
    publication_language: "en",
    anonymization_level: "none",
    active_variant: "a",
    active_title_variant: "a",
    auto_optimize: false,
    is_published: false,
    seo_keywords: ["devops", "platform", "hamburg"],
    user_id: OWNER,
    assigned_to: OWNER,
    created_at: iso(12),
    updated_at: iso(1),
  },
  {
    id: "job-5",
    title: "Senior Data Scientist (m/w/d)",
    client_id: "c-1",
    location: "Berlin / Remote",
    status: "Active",
    employment_type: "Full-time",
    experience_level: "Senior",
    salary_range: "75.000 – 90.000 €",
    skills: ["Python", "PyTorch", "MLOps", "SQL"],
    description: "Drive ML initiatives for predictive logistics.",
    requirements: "4+ years applied ML, strong Python and MLOps.",
    responsibilities: "Build and deploy ML models, partner with product.",
    benefits: "Remote-first, conference budget, GPU resources.",
    publication_status: "draft",
    publication_language: "de",
    anonymization_level: "none",
    active_variant: "a",
    active_title_variant: "a",
    auto_optimize: false,
    is_published: false,
    seo_keywords: ["data science", "ml", "berlin"],
    user_id: OWNER,
    assigned_to: OWNER,
    created_at: iso(6),
    updated_at: iso(1),
  },
];

const placements: Row[] = [
  {
    id: "pl-1",
    candidate_id: "cand-1",
    job_id: "job-1",
    stage: "Vorgestellt",
    match_score: 92,
    skills_score: 95,
    experience_score: 90,
    salary_score: 85,
    match_summary: "Excellent fit for the lead backend role.",
    match_strengths: ["Deep JVM expertise", "Cloud-native experience", "Leadership"],
    match_gaps: ["Limited Go experience"],
    match_risks: [],
    match_reasons: ["Skills alignment", "Seniority match"],
    from_ai_match: true,
    follow_up: false,
    notes: [],
    user_id: OWNER,
    created_at: iso(8),
    updated_at: iso(1),
  },
  {
    id: "pl-2",
    candidate_id: "cand-2",
    job_id: "job-2",
    stage: "Interview 1",
    match_score: 88,
    skills_score: 90,
    experience_score: 85,
    salary_score: 88,
    match_summary: "Strong embedded match for MedTech.",
    match_strengths: ["Embedded C/C++", "Regulated industry exposure"],
    match_gaps: ["No prior MedTech certification"],
    match_risks: ["Relocation required"],
    match_reasons: ["Domain fit"],
    from_ai_match: true,
    follow_up: true,
    notes: [],
    user_id: OWNER,
    created_at: iso(6),
    updated_at: iso(1),
  },
  {
    id: "pl-3",
    candidate_id: "cand-3",
    job_id: "job-3",
    stage: "Ready2Send",
    match_score: 84,
    skills_score: 88,
    experience_score: 80,
    salary_score: 82,
    match_summary: "Good frontend match for the banking project.",
    match_strengths: ["React/TS", "Design systems"],
    match_gaps: ["No finance domain experience"],
    match_risks: [],
    match_reasons: ["Tech stack alignment"],
    from_ai_match: false,
    follow_up: false,
    notes: [],
    user_id: OWNER,
    created_at: iso(4),
    updated_at: iso(1),
  },
  {
    id: "pl-4",
    candidate_id: "cand-5",
    job_id: "job-5",
    stage: "Shared",
    match_score: 90,
    skills_score: 92,
    experience_score: 82,
    salary_score: 90,
    match_summary: "Great data science match.",
    match_strengths: ["Modern ML stack", "MLOps mindset"],
    match_gaps: ["Junior on people leadership"],
    match_risks: [],
    match_reasons: ["Strong technical fit"],
    from_ai_match: true,
    follow_up: false,
    shared_at: iso(2),
    notes: [],
    user_id: OWNER,
    created_at: iso(3),
    updated_at: iso(1),
  },
];

const ai_matches: Row[] = [
  {
    id: "aim-1",
    candidate_id: "cand-4",
    job_id: "job-4",
    match_score: 87,
    status: "pending",
    match_summary: "DevOps profile aligns well with the platform role.",
    match_strengths: ["Terraform", "Kubernetes", "AWS"],
    match_gaps: ["German B1 only"],
    user_id: OWNER,
    created_at: iso(2),
    updated_at: iso(1),
  },
  {
    id: "aim-2",
    candidate_id: "cand-1",
    job_id: "job-5",
    match_score: 71,
    status: "pending",
    match_summary: "Backend strength, partial data science overlap.",
    match_strengths: ["Python basics", "SQL"],
    match_gaps: ["No ML production experience"],
    user_id: OWNER,
    created_at: iso(2),
    updated_at: iso(1),
  },
];

const tasks: Row[] = [
  {
    id: "task-1",
    title: "Call Julia Sommer about lead role",
    description: "Discuss the Nordwind lead backend opportunity.",
    completed: false,
    deadline: iso(-1),
    candidate_id: "cand-1",
    job_id: "job-1",
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(3),
    updated_at: iso(1),
  },
  {
    id: "task-2",
    title: "Send Mehmet's profile to MedTech",
    description: "Prepare and share the candidate dossier.",
    completed: false,
    deadline: iso(0),
    candidate_id: "cand-2",
    job_id: "job-2",
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(2),
    updated_at: iso(1),
  },
  {
    id: "task-3",
    title: "Follow up with Rheinland Finanz",
    description: "Check feedback on frontend shortlist.",
    completed: true,
    deadline: iso(5),
    candidate_id: null,
    job_id: "job-3",
    assigned_to: OWNER,
    user_id: OWNER,
    created_at: iso(7),
    updated_at: iso(4),
  },
];

const applications: Row[] = [
  {
    id: "app-1",
    job_id: "job-2",
    first_name: "Lukas",
    last_name: "Brandt",
    email: "lukas.brandt@example.com",
    phone: "+49 151 22334455",
    status: "neu",
    cover_letter: "I am very interested in the embedded developer position...",
    cv_url: null,
    user_id: OWNER,
    created_at: iso(1),
    updated_at: iso(1),
  },
  {
    id: "app-2",
    job_id: "job-2",
    first_name: "Nina",
    last_name: "Hoffmann",
    email: "nina.hoffmann@example.com",
    phone: "+49 152 66778899",
    status: "in_review",
    cover_letter: "With 6 years of firmware experience...",
    cv_url: null,
    user_id: OWNER,
    created_at: iso(3),
    updated_at: iso(2),
  },
];

const activity_logs: Row[] = [
  {
    id: "act-1",
    candidate_id: "cand-1",
    activity_type: "status_change",
    description: "Recruiting status changed to Ready2Push",
    user_id: OWNER,
    created_at: iso(2),
  },
  {
    id: "act-2",
    candidate_id: "cand-2",
    activity_type: "note",
    description: "Documents sent to client",
    user_id: OWNER,
    created_at: iso(4),
  },
  {
    id: "act-3",
    candidate_id: "cand-5",
    activity_type: "created",
    description: "Candidate added to the system",
    user_id: OWNER,
    created_at: iso(10),
  },
];

const industries: Row[] = [
  { id: "ind-1", name: "Software & IT", user_id: OWNER, created_at: iso(120) },
  { id: "ind-2", name: "Healthcare & MedTech", user_id: OWNER, created_at: iso(120) },
  { id: "ind-3", name: "Finance & Insurance", user_id: OWNER, created_at: iso(120) },
  { id: "ind-4", name: "Mobility & Automotive", user_id: OWNER, created_at: iso(120) },
  { id: "ind-5", name: "Manufacturing", user_id: OWNER, created_at: iso(120) },
  { id: "ind-6", name: "E-Commerce & Retail", user_id: OWNER, created_at: iso(120) },
];

const skills: Row[] = [
  "Java", "Spring Boot", "Kubernetes", "AWS", "React", "TypeScript",
  "Python", "PyTorch", "C++", "Terraform", "PostgreSQL", "GraphQL",
].map((name, i) => ({
  id: `skill-${i + 1}`,
  name,
  user_id: OWNER,
  created_at: iso(120),
}));

const languages: Row[] = [
  "German", "English", "French", "Italian", "Spanish", "Polish", "Turkish", "Swedish",
].map((name, i) => ({
  id: `lang-${i + 1}`,
  name,
  user_id: OWNER,
  created_at: iso(120),
}));

const blog_posts: Row[] = [
  {
    id: "blog-1",
    title: "5 Trends Shaping Tech Recruiting in 2026",
    slug: "tech-recruiting-trends-2026",
    content:
      "# 5 Trends Shaping Tech Recruiting\n\nThe hiring landscape keeps evolving...",
    excerpt: "A look at the biggest shifts in technical hiring this year.",
    status: "published",
    author: "Alex Admin",
    tags: ["recruiting", "trends"],
    user_id: OWNER,
    created_at: iso(14),
    updated_at: iso(7),
    published_at: iso(7),
  },
  {
    id: "blog-2",
    title: "How to Write Job Posts That Convert",
    slug: "job-posts-that-convert",
    content: "# Writing Better Job Posts\n\nClarity beats cleverness...",
    excerpt: "Practical tips for writing job ads candidates actually respond to.",
    status: "draft",
    author: "Morgan Manager",
    tags: ["content", "jobs"],
    user_id: OWNER,
    created_at: iso(5),
    updated_at: iso(2),
    published_at: null,
  },
];

const invitations: Row[] = [
  {
    id: "inv-1",
    email: "newhire@demo.test",
    token: "demo-invite-token",
    status: "pending",
    role: "user",
    invited_by: OWNER,
    created_at: iso(3),
    expires_at: iso(-11),
  },
];

const market_radar_profiles: Row[] = [
  {
    id: "mrp-1",
    name: "Berlin Backend Talent",
    keywords: ["Java", "Kotlin", "Spring"],
    location: "Berlin",
    is_active: true,
    user_id: OWNER,
    created_at: iso(20),
    updated_at: iso(2),
  },
];

// Tables that exist in the schema but start empty in the demo.
const EMPTY_TABLES = [
  "access_logs",
  "ai_cache",
  "ai_matching_jobs",
  "candidate_badge_assignments",
  "candidate_badges",
  "commute_cache",
  "dismissed_suggestions",
  "external_search_jobs",
  "interview_prep_documents",
  "job_analytics",
  "market_radar_scans",
  "publication_analytics",
  "publication_audit_log",
  "publication_blacklist",
  "publication_rules",
  "rejection_reasons",
  "saved_filters",
  "status_configurations",
  "task_folders",
];

export function buildSeedDatabase(): DemoDatabase {
  const db: DemoDatabase = {
    profiles,
    user_roles,
    clients,
    contact_persons,
    candidates,
    jobs,
    placements,
    ai_matches,
    tasks,
    applications,
    activity_logs,
    industries,
    skills,
    languages,
    blog_posts,
    invitations,
    market_radar_profiles,
  };
  for (const t of EMPTY_TABLES) {
    if (!db[t]) db[t] = [];
  }
  // Deep clone so the in-memory store never mutates the seed templates.
  return JSON.parse(JSON.stringify(db));
}
